#ifndef TIMER_CONF_TEMPLATE
#define TIMER_CONF_TEMPLATE

#define INVALID_SLOT				255
#define UNINIT_STATUS				2

#define MAX_PLANS						10
#define MAX_TIMES_PER_PLAN	6

#define ENABLE_USER_INTERFACE

#endif